[build]
  command = "cd Mini_Project && npm install && npm run build"
  publish = "Mini_Project/.output/public"

[build.environment]
  NODE_VERSION = "20"
  NITRO_PRESET = "netlify"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
